/*
 * Swagger Eazy Pay
 * Dies ist die Swagger API für die App Eazy Pay, welches es ermöglicht den Usern/Kunden Bezahlvorgänge kontaktlos zu betätigen
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.auth;

public enum OAuthFlow {
    accessCode, implicit, password, application
}
